# —— 列名映射（按你的报表列名填写） ——
columns_map:
  search_term: "Customer Search Term"
  clicks: "Clicks"
  impressions: "Impressions"
  spend: "Spend"
  sales: "7 Day Total Sales"
  orders: "7 Day Total Orders (#)"
  campaign: "Campaign Name"
  ad_group: "Ad Group Name"

# —— 常规优化阈值（先宽松，避免结果空） ——
target_acos: 0.50
min_clicks: 5
min_conversions: 1
harvest_threshold: 0.05

# —— 早期否定扫描（样本少也能给出建议） ——
negatives_scan:
  mode: conservative           # conservative / aggressive
  min_clicks_no_order: 1       # 点击≥1 且无订单 → 候选
  min_ctr: 0.0                 # 低点击期先不设CTR门槛
  match_type: "negative exact" # 上传草稿默认精确否定
  patterns:
    UNRELATED_CONTEXT: ["car","vehicle","reptile","aquarium"]
    ACCESSORY_ONLY: ["replacement","spare","adapter"]
    PRICE_SEEKER: ["cheap","budget","free"]
    GENERIC_LOW_INTENT: ["kit","set"]
    MISMATCH_SPEC: ["1 gallon","10cm","12v"]

# —— 词库维护（自动建议） ——
lexicon:
  min_clicks_for_bad: 1
  min_clicks_for_good: 1
  suggest_top_k: 50
  ngram_max: 2
  min_bad_freq: 2
  whitelist: ["your_brand"]
  stopwords: ["for","with","the","and","a","to","of"]
